### ISSUE TITLE
Setup login link modal 

### ISSUE THREAD

**Issue by jarehart** [Cavendo/mmr-public#4]
Can we get the login link to work exactly as it does on mymediaroom.com currently?

**Comment by martylouis** [comment]
Sure, but what will be the form action address?

Current setup:

```
<form name="login" action="/login2.aspx" method="post" class="form-login" id="form-login">...</form>
```

**Comment by jarehart** [comment]
http://cp.mmrdev.com/login2.aspx for now.


On Jan 9, 2015, at 14:11, Marty Thierry <notifications@github.com> wrote:

Sure, but what will be the form action address?

Current setup:

<form name="login" action="/login2.aspx" method="post"
class="form-login" id="form-login">...</form>

—
Reply to this email directly or view it on GitHub
<https://github.com/Cavendo/mmr-public/issues/4#issuecomment-69382862>.

**Comment by martylouis** [comment]
This is good to go.
